name: bonsai-MLO
dependencies:
- python=3.7
- pip=19.1.1
- jupyter=1.0.0
- ffmpeg=4.2.2
- pip:
  - cryptography==2.9.2
  - numpy==1.15.2
  - matplotlib==3.0.3
  - pandas==0.24.2
  - microsoft-bonsai-api==0.1.1
  - scipy==1.3.0
  - bonsai-cli>=1.0.0
  - ortools==9.0.9048
  - sklearn
  - simpy==4.0.1
  - python-dotenv==0.19.0
  - networkx==2.6.2
  - Kqlmagic==0.1.113.post1

